### ISSUE TITLE
Regression datasets mislabeled as classification?

### ISSUE THREAD

**Issue by amueller** [openml/OpenML#630] opened 2018-02-19 21:37 UTC
I think all of these are regression:
https://www.openml.org/search?q=qualities.NumberOfClasses%3Agt%3B150&type=data

but they report a very high number of classes instead.

Btw, this would be a good query for a quality check bot.
Do we have an issue to list possible queries?

**Comment by amueller** [comment] 2018-02-20 23:46
Is @ArlindKadra working on https://github.com/openml/openml-serverdata-quality-bot or something else?
Looks like they are working on https://github.com/ArlindKadra/CheckDatasets ?

So there's two projects, neither of which is linked to OpenML in an easy-to-find way?

I might repeat myself here, but information should not be in issues (I wanted an issue to collect feature requests, not document behavior).

The checker is implemented in Java? Is it meant to run on the server or by someone else?

**Comment by ArlindKadra** [comment] 2018-02-21 00:42
@joaquinvanschoren @janvanrijn @amueller 
Sure, I can add a check for datasets which have a high number of classes. 
@amueller 
The checker is implemented in java. It is meant to be run on the server. I am working on the later, the code will be moved in the upcoming days to an OpenMl repository.

**Comment by mfeurer** [comment] 2018-02-21 07:51
@amueller should the https://github.com/openml/openml-serverdata-quality-bot be made public and more documented once it's ready?

**Comment by amueller** [comment] 2018-02-21 15:28
@mfeurer I think both should be documented and made public ;) Though maybe documented in the dev docs? Is idea behind that one to tag, or just to report and then clean manually?

@ArlindKadra how will the queries be specified? And what will happen with the results? It's very likely that other people want to contribute rules.

**Comment by ArlindKadra** [comment] 2018-02-21 21:45
@amueller In my case, I am using the apiconnector by @janvanrijn. It offers plenty of functions which on the internal build different queries and if more detailed results are required, different filters can be applied. The initial idea was to just log the results, as for the result handling part @janvanrijn can give you a better explanation. 
Further rules can be incorporated easily.

**Comment by joaquinvanschoren** [comment] 2018-09-22 18:34
Picking up on regression again. Currently, it seems that datasets with a numeric default target get a number_of_classes equal to the total number of unique numeric values (of to millions). That doesn't really make sense? Should be fixed so that the number_of_classes is equal to '-1'? Or NA?

**Comment by joaquinvanschoren** [comment] 2018-09-22 19:34
did a PR

**Comment by janvanrijn** [comment] 2018-09-22 19:40
If that is the case, that is a huge bug. I checked your pr. Looks good, except for one suggestion. In case of regression, shall we make number of classes is null (consistency)?

**Comment by janvanrijn** [comment] 2018-09-22 19:41
Thanks for the pr btw! Its great to have a second pair of eyes on the eval engine

**Comment by janvanrijn** [comment] 2018-09-22 19:48
Btw what happens in the case of multilabel?

**Comment by joaquinvanschoren** [comment] 2018-09-22 19:51
I thought about setting it to null, but that means that there would be no way to search for regression datasets at the moment. Ideally, we have a quality like DefaultTargetType = Numeric/Nominal, but I'm not sure if we can handle string qualities.
Setting the number of classes to 0 seems to be much easier at the moment.

Yes, you can search for regression tasks, but if you want to create regression tasks on datasets where no tasks are created yet, that doesn't help you. Also, if you want to search for 'all regression tasks with less than 500 instances' that also doesn't work via the task search. I actually needed that earlier today.

**Comment by joaquinvanschoren** [comment] 2018-09-22 19:56
Multi-label: I don't know. I think it would be ok to set the number of classes to null in that case to avoid confusion. Or, if possible, we could return an array with the class counts of every target?

**Comment by janvanrijn** [comment] 2018-09-23 08:11
Let's discuss multilabel datasets in a separate issue. These are not integrated well and require some attention

**Comment by amueller** [comment] 2018-09-24 19:11
so setting class numbers to 0 for now?

**Comment by amueller** [comment] 2018-10-22 17:33
This has been solved, right?

**Comment by janvanrijn** [comment] 2018-10-22 17:39
See #528

Yes, it has been solved code-wise, I am still struggling to understand why some datasets had incorrect values this morning. I would prefer to close this issue and leave #528 open for a while, until I have checked all the queries that I posted there again.

**Comment by amueller** [comment] 2018-10-22 17:44
ok keep open whatever you think is most useful to move forward.

**Closed** 2018-10-22 17:52 UTC
