### ISSUE TITLE
Different outcomes of listOMLRunEvaluations (With and without runtime)

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#426] opened 2017-06-13 13:07 UTC
_From @PhilippPro on June 13, 2017 12:50_

For some Runs we get also time information now with listOMLRunEvaluations. But only for some.
Is this intended to be like that?

Code:
```
listOMLRunEvaluations(run.id = 2253351)
listOMLRunEvaluations(run.id = 2306596)
```

_Copied from original issue: openml/openml-r#367_

**Comment by giuseppec** [comment] 2017-06-13 13:07
Yes, because the package just shows the information that the server gives us. See also https://www.openml.org/r/2253351 and https://www.openml.org/r/2306596 . 
Maybe the server guys fixed the the runtime bug between the run 2253351 and 2306596. And maybe they now have to run the server evaluation engine again to the previous runs so that they also show the runtime info. @janvanrijn , @joaquinvanschoren can you confirm?

**Comment by joaquinvanschoren** [comment] 2017-06-14 12:38
This is fixed in the new evaluator. We still need to identify the runs without runtime info and reindex them @janvanrijn

**Comment by joaquinvanschoren** [comment] 2017-06-14 12:41
Closing because duplicate of #412

**Closed by joaquinvanschoren** 2017-06-14 12:41 UTC
