### ISSUE TITLE
listing calls return invalid json

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#932] opened 2019-02-22 08:59 UTC
Some strange issues:

This seems to work: https://www.openml.org/api/v1/json/task/list/limit/6 

However, this https://www.openml.org/api/v1/json/task/list/limit/7 returns invalid json (validated by https://jsonlint.com)

Similar issues were reported here https://github.com/openml/openml-r/issues/433 and https://github.com/openml/openml-r/issues/434 by @thiloshon

**Comment by janvanrijn** [comment] 2019-02-22 09:10
Seems that a tailing `}` is missing. 

This is the function that we use to convert XML to JSON:
https://github.com/openml/OpenML/blob/master/openml_OS/core/MY_Api_Model.php#L25

This is an additional json template for tasks
https://github.com/openml/OpenML/blob/master/openml_OS/views/pages/api_new/v1/json/tasks.tpl.php

I suspect (and seriously hope) the problem is in the latter.

**Comment by giuseppec** [comment] 2019-02-22 13:12
Not sure because everything worked fine a few days ago (and both the converter and the template seem to be unchanged for several months). So I suppose some recent change caused this bug?
And it also appears to happen with other listing calls, so not only the task/list is broken.

**Comment by janvanrijn** [comment] 2019-02-22 19:53
OpenML attempts to return correct HTTP headers, like the size of a HTTP response. Apparently, this header has become corrupt (and returns 2 spaces too few). I have applied a hotfix on the main server. This needs to be fixed in a more rigorous way though.

**Comment by joaquinvanschoren** [comment] 2019-02-22 22:58
Found the bug and fixed it. The content-length of the JSON was correct, but the server was returning 2 additional newlines. These were caused by an empty line at the end of 2 recently updated files.

**Comment by giuseppec** [comment] 2019-02-23 14:43
Thx ;). Another related (but different) issue is this https://test.openml.org/api/v1/json/study/list/ (test server gives PHP error) and the main server gives an empty list: https://www.openml.org/api/v1/json/study/list/
Maybe this is due to the recent improvements on studies?

**Comment by janvanrijn** [comment] 2019-02-23 16:47
Listing function is nit unit tested yet. (haven't implemented it in python api) seems like a php bug. Will fix on monday.

**Comment by joaquinvanschoren** [comment] 2019-07-09 13:23
seems fixed :)

**Closed by joaquinvanschoren** 2019-07-09 13:23 UTC
