### ISSUE TITLE
Duplicated tasks that only differ based on evaluation.measures

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#841] opened 2018-10-26 07:31 UTC
The two tasks https://www.openml.org/t/2 and https://www.openml.org/t/145952 are both based on the `anneal` data. However, the first one uses the predictive_accuracy and the second one uses the precision. This seems to be the only difference between both tasks? Ok, probably they also have different train-test splits. If they would use the same train-test splits, these two tasks could be merged, right? Since OpenML computes all evaluation measures anyway.
I found a lot of such "duplicated" tasks which might be confusing for users when they want to select results of runs. 

Suppose the following use case (see e.g. https://github.com/openml/openml-r/issues/421): I want to get benchmark results that are based on "Supervised Classification" UCI data sets (I don't care about evaluation measure yet, just want all runs I can get). 

Ok, cool I can do this: 
1) Get all tasks based on UCI datasets with estimation.procedure = "10-fold Crossvalidation" using https://www.openml.org/api/v1/json/task/list/type/1/data_tag/uci/status/active
2) Shit, there are still so many duplicated tasks based on the same data. Ok, I can get rid of tasks that use (i) a different target feature and (ii) different cost matrices. 
3) There are still some tasks that only differ w.r.t. an evaluation measure (mostly `predictive_accuracy`, `precision` and an empty value `NA` - **does anyone know why we have this?**). Anyway, for which of those tasks should I now get the runs? Most probably I want to select the tasks that have more runs?However, I now have to manually look this up as this info is not shown in task/list.

Solution: Maybe we can show also the number of runs in `task/list`?

**Comment by hildeweerts** [comment] 2018-10-26 11:33
There has been a discussion about this problem in #718 (just FYI).

**Comment by joaquinvanschoren** [comment] 2018-10-29 19:47
Shall we close this because it is a duplicate of #718?

**Comment by janvanrijn** [comment] 2018-10-29 19:48
I agree.

**Closed by janvanrijn** 2018-10-29 19:48 UTC
