### ISSUE TITLE
Missing data splits (arff)?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#240] opened 2016-03-08 08:59 UTC
Hi, 

the API call http://api_new.openml.org/v1/task/261, for example, has a data_splits slot that should contain the url to the arff file containing the data splits. For this task, the url is: http://www.openml.org/api_splits/get/261/Task_261_splits.arff, however opening this url returns an `arff` file with the following content:

```
{"error":"For input string: """}
```

Not sure if there are other tasks with this error, but currently our unit tests for the R-package are failing because we are using this task 261 (I think a week ago the unit tests did not fail because of this).

**Comment by giuseppec** [comment] 2016-03-08 09:13
This seems to be related to https://github.com/openml/website/issues/25. We have to make sure that all .arff files on the server are valid to avoid that such .arff files are downloaded that contain simply a text like `{"error":"For input string: """}` or `Task not providing datasplits.`.

Btw. from https://github.com/openml/website/issues/25 another issue occurs: Task 7529 is using data set 1418, however http://api_new.openml.org/v1/data/1418 returns:

```
<oml:error>
<oml:code>111</oml:code>
<oml:message>Unknown dataset</oml:message>
</oml:error>
```

How can there be a Task available that uses an unknown dataset? Shouldn't such tasks be removed?

**Comment by joaquinvanschoren** [comment] 2016-03-08 09:29
Those are separate issues. The first is due to a recent simplification we
made on the server. This seems to fail for talks with holdouts. We'll fix
this asap.

The second uses 'testontrainingdata' and hence doesn't have data splits.
I'll respond in the other issue thread.

The third issue is a dataset that is now private. You should have gotten
that task from the /task/list api. Will fix that too.

**Comment by giuseppec** [comment] 2016-03-10 14:05
Okay, I will change the task id in our unit test so that we are not failing on travis just because of issue 1) and 2) you mentioned. I also added antoher unit test that will fail when these two issues are fixed, so that I will be remembered that I might change a few things with regard to those two issues.

Regarding 3), the task/list API gives me:
```
<oml:task><oml:task_id>7529</oml:task_id>
<oml:task_type>Clustering</oml:task_type>
<oml:did>1418</oml:did>
<oml:name>physionet_tachycardia</oml:name>
<oml:status>active</oml:status>
<oml:format>ARFF</oml:format>
...
```

**Comment by berndbischl** [comment] 2016-03-10 14:43
@larskotthoff @giuseppec @joaquinvanschoren 
Can we maybe ask Lars to add a simple check for this to our jenkins test suite, please?

**Comment by larskotthoff** [comment] 2016-03-10 17:11
What exactly do you want me to check?

**Comment by berndbischl** [comment] 2016-03-10 17:28
basically that the splits exist and are parseable. 
although that kinda needs to be the case if you download every task, correct? 
which you already do?

**Comment by larskotthoff** [comment] 2016-03-10 17:38
Yes. Any existing code you want me to run?

**Comment by larskotthoff** [comment] 2016-03-10 17:46
Sorry, s/existing/additional/ -- yes, I already download and parse everything, but it sounded like you want me to do something else as well :)

**Comment by giuseppec** [comment] 2016-03-10 19:13
Yes. task != dataset. The error happens for the data splits (not for the dataset), which are also stored as .arff files in the corresponding task. But I like the idea to do tests also for the data split .arff files with jenkins. If we hadn't task 261 in our R unit tests, this bug would have been still undiscovered.

**Comment by janvanrijn** [comment] 2016-03-11 10:14
A bug slipped in while updating the evaluation engine. Should be fixed by now.

**Comment by joaquinvanschoren** [comment] 2016-03-11 10:19
Can you run R code in Jenkins? If so it would basically be:

library(mlr)
library(OpenML)
tasks = listOMLTasks() # Fetches all tasks
for (id in tasks["task.id"]) {
   task = getOMLTask(task.id = 261)
   lrn = makeLearner("classif.rpart")
   res = runTaskMlr(task, lrn)
}

If splits are broken it will throw a cryptic error like:
Error in rep == r: comparison (1) is possible only for atomic and list types

Is there a faster classifier than RPART in mlr?

Cheers,
Joaquin

**Comment by giuseppec** [comment] 2016-03-11 10:26
Maybe this is better (and faster):

```r
library(mlr)
library(OpenML)
tasks = listOMLTasks() # Fetches all tasks
for (id in tasks$task.id) {
  task = downloadOMLObject(id = id, object = "task")
  if (!is.null(task$files$datasplits.arff$path))
   ds = arff.reader(task$files$datasplits.arff$path)
}
```

**Comment by joaquinvanschoren** [comment] 2016-03-11 10:32
This works now: http://www.openml.org/api_splits/get/261/Task_261_splits.arff
I also tested it in R and it works fine (after deleting the cache)

Shall we close this or keep it open until Jenkins in updated?

**Comment by joaquinvanschoren** [comment] 2016-03-11 10:39
Giuseppe's version is indeed better

**Comment by giuseppec** [comment] 2016-03-11 10:40
Maybe we can let this open here and also do checks for the data splits with respect to this aspects:
- if I remember well, `rowid` should be 0-based (not 1-based). Maybe we should check if this holds for all data splits (I am not sure, but it might be that at the beginning I have seen cases where this was not the case)?
- @joaquinvanschoren are there other aspects which MUST hold for data splits that we could check for?

**Comment by berndbischl** [comment] 2016-03-11 11:20
Why dont we parse the whole task? That would check for other potential problems as well.
So I would suggest Joaquin's solution.

**Comment by berndbischl** [comment] 2016-03-11 11:21
One can discuss whether one wants the rpart call in there. But doing this actually ensures that we can technically "learn" on the task. So I am for it, unless we detect further problems with this.

**Comment by berndbischl** [comment] 2016-03-11 11:22
Also note that we probably need a 2nd jenkins job for this, correct? If we only add this at the end of the current one, it will never run if parsing a dataset before fails?

**Comment by joaquinvanschoren** [comment] 2016-03-11 11:25
Ok, but note that you would need alternatives for regression, data stream,
clustering, survival tasks as well. I only covered the classification task
here.

**Comment by berndbischl** [comment] 2016-03-11 11:26
> Ok, but note that you would need alternatives for regression, data stream,
> clustering, survival tasks as wel

Your are right. Therefore leave it out. But being able to parse the task already checks a lot.

**Comment by giuseppec** [comment] 2016-03-11 11:26
If you don't do the rpart call, the data splits won't be parsed (because this happens in the runMlrTask function). So either we use joaquin's solution including the rpart call (we will get errors if rpart fails for some reason). Or we try this, which parses also the task.xml (and we don't have to fit a model):

```
library(mlr)
library(OpenML)
tasks = listOMLTasks() # Fetches all tasks
for (id in tasks$task.id) {
  task = downloadOMLObject(id = id, object = "task")
  get.task = getOMLTask(task.id = id)
  if (!is.null(task$files$datasplits.arff$path))
   ds = arff.reader(task$files$datasplits.arff$path)
}
```

If we want to check model-fitting things, we could do this as an extra jenkins call.

**Comment by berndbischl** [comment] 2016-03-11 11:26
We should that later add jenkins jobs specific for classification, regresssion and so on.

**Comment by berndbischl** [comment] 2016-03-11 11:27
> If you don't do the rpart call, the data splits won't be parsed (because this happens in the runMlrTask function).

Huh? Thats sounds strange. We should change that anyhow.

**Comment by giuseppec** [comment] 2016-03-11 11:35
Sorry, disregard this statement, it is not true (parsing happens in `getOMLTask`).

**Comment by joaquinvanschoren** [comment] 2016-03-11 11:39
Hmm, I did not get the error when I did `getOMLTask`, that's why I did the
run.

**Comment by joaquinvanschoren** [comment] 2016-03-11 11:40
Hmm, never mind, that could easily be explained by caching

**Comment by larskotthoff** [comment] 2016-03-11 17:27
Not sure if I got this. So you want me to create a new Jenkins job with the code that just downloads and parses all tasks?

**Comment by berndbischl** [comment] 2016-03-11 17:28
You did get it indeed.

**Comment by larskotthoff** [comment] 2016-03-11 17:49
`downloadOMLObject` isn't exported.

**Comment by berndbischl** [comment] 2016-03-11 19:23
This thread became complicated, and I dont really understand why. 
For concreteness sake:

1) 
Please create a jenkins job which runs this.

```
library(mlr)
library(OpenML)
tasks = listOMLTasks() # Fetches all tasks
for (id in tasks["task.id"]) {
   task = getOMLTask(task.id = id)
}
```

If the jobs fails, the ID and error message should be reported. 

2) 
Later we should create additional jobs, where we run ML models on the downloaded task. For now 1) s might be enough.

All agree?

**Comment by berndbischl** [comment] 2016-03-11 19:25
@giuseppec 
Maybe try to add a few lines of code, to check additional expectations on the task object you deem important. Keep it simple and check the most important stuff only.

**Comment by larskotthoff** [comment] 2016-03-11 19:48
Ok, that's running fine (https://hagakure.cs.ubc.ca:2893/job/OpenML-tasks/7/console).

**Comment by joaquinvanschoren** [comment] 2016-03-11 20:09
Thanks!
Close this now?

**Comment by joaquinvanschoren** [comment] 2016-03-11 23:03
Does this also check whether the tasks only use 0-based splits?

**Comment by larskotthoff** [comment] 2016-03-11 23:55
Nope.

**Comment by larskotthoff** [comment] 2016-03-11 23:56
Oh and I'm getting

Downloading from 'http://api_new.openml.org/v1/task/34' to '/tmp/RtmpLw07wM/cache/tasks/34/task.xml'
Error in parseXMLResponse(content, msg = paste0("Getting ", gsub("_",  : 
  Error (code = 151) in server / XML response for: Getting task
		Unknown task.
		
Calls: getOMLTask ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>

**Comment by joaquinvanschoren** [comment] 2016-03-12 00:59
Does that happen consistently? It may be that the database was overwhelmed.

**Comment by larskotthoff** [comment] 2016-03-12 01:04
It got past that this time, running now.

**Comment by larskotthoff** [comment] 2016-03-12 01:04
Spoke too soon:

Downloading from 'http://api_new.openml.org/v1/data/52' to '/tmp/RtmpZrNmnW/cache/datasets/52/description.xml'
Downloading from 'http://www.openml.org/data/download/52/dataset_52_trains.arff' to '/tmp/RtmpZrNmnW/cache/datasets/52/dataset.arff'
Error in .jnew("weka/core/Instances", .jcast(reader, "java/io/Reader")) : 
  java.io.IOException: keyword @relation expected, read Token['{'], line 1
Calls: getOMLTask
Execution halted

**Comment by joaquinvanschoren** [comment] 2016-03-12 01:36
http://www.openml.org/data/download/52/dataset_52_trains.arff seems fine.
Could you clear your local cache?

**Comment by larskotthoff** [comment] 2016-03-12 03:03
Now I get the same for dataset 40. Looks like the server doesn't like me :(

**Comment by giuseppec** [comment] 2016-03-12 09:43
It sounds like this thing here: https://github.com/openml/OpenML/issues/239

**Comment by joaquinvanschoren** [comment] 2016-03-14 01:16
I think we can close this. #239 remains open.

**Comment by giuseppec** [comment] 2016-03-24 09:03
At least task `267` (http://www.openml.org/api_splits/get/267/Task_267_splits.arff) and `1973` (http://www.openml.org/api_splits/get/1973/Task_1973_splits.arff) have still this error: 

```
{"error":"For input string: """}
```

I think there will be more such tasks... could you please fix them?

**Comment by giuseppec** [comment] 2016-03-24 09:26
@joaquinvanschoren it seems that this occurs very often for tasks with "33% Holdout set" as estimation.procedure. Could you reopen this issue?

**Comment by berndbischl** [comment] 2016-03-24 09:51
@giuseppec @larskotthoff 
Is this now tested on jenkins? IMHO it makes no sense to discuss individual object ids here, but we must have a general test procedure!

**Comment by larskotthoff** [comment] 2016-03-24 16:00
Well it's tested in the sense that there's a job on Jenkins that tries to download everything. That said, it never actually got very far because the server keeps returning errors.

**Comment by berndbischl** [comment] 2016-03-24 16:05
ok so the server guys should fix that :)
but at least we WOULD in principle detect problems like discussed in this thread

**Comment by larskotthoff** [comment] 2016-03-24 16:08
At the moment the job only downloads stuff, it doesn't check anything beyond that. That said, any additional things will be easy enough to add.

**Comment by joaquinvanschoren** [comment] 2016-10-03 07:56
I propose we close this because the issue itself is fixed, then open a new issue about the CI.

**Closed by joaquinvanschoren** 2016-10-03 07:56 UTC
Labels: bug, priority: high
