### ISSUE TITLE
function filter for evaluation list

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#414] opened 2017-05-09 14:12 UTC
In https://github.com/openml/openml-r/issues/275 it was mentioned that this should work but doesn't: https://www.openml.org/api/v1/xml/evaluation/list/tag/mlrRandomBot/function/area_under_roc_curve

Is there any progress?

**Comment by joaquinvanschoren** [comment] 2017-06-05 21:57
This is fixed. Waiting for Jan to review the PR.

**Comment by joaquinvanschoren** [comment] 2017-06-05 21:58
Closing, as this is a duplicate of #423

**Closed by joaquinvanschoren** 2017-06-05 21:58 UTC
