### ISSUE TITLE
Listing no runtime for runs

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#425] opened 2017-06-06 10:19 UTC
Hi, the XML from https://www.openml.org/api/v1/json/evaluation/list/run/1815726 does not provide any info w.r.t. the runtime (See https://github.com/openml/openml-r/issues/357). I remember that this was possible some time ago.

**Comment by joaquinvanschoren** [comment] 2017-06-06 10:42
This is a duplicate of https://github.com/openml/OpenML/issues/412

**Comment by joaquinvanschoren** [comment] 2017-06-06 10:48
The problem is not that runtimes are not returned, but that they are not stored in the first place. We'll fix that and reimport the runs.

**Closed** 2017-06-06 10:48 UTC
