### ISSUE TITLE
Invalid arff files parsed

### ISSUE THREAD

**Issue by jaksmid** [openml/OpenML#176] opened 2015-02-21 13:37 UTC
Hi Joaquin and all,

I was looking at the dataset with the ID 674 called chscase_demand. The system was able to somehow parsed it.

I believe the file is not a valid arff file and should be identified as such.
If you inspect the files, you can see double commas in rows 66 to 89. The last four rows are missing these. The number of values is the same in each column - 11. 

As an example I will compare column 89 and 90:
83,239.6,3.764,,9930,2.026,3.297,3.626,1.041,1.021,1.062,6889					
84,244.7,3.707,10421,2.085,3.757,3.852,1.038,1.050,1.117,7056					

First three columns are ok and looks the distribution is similar.
Fourth column row 89: double commas, therefore missing value
Fourth column row 89: number 10421 - this is similr to the number in the fifth column of the row 89.

Again, its looks like it is badly aligned and double commas are extra as the number of values is same per row, but the number of commas is different.

Could you comment on how it is parsed as I believe this is invalid format?
Many thanks,
Jakub

**Comment by mfeurer** [comment] 2015-02-24 10:32
Hi,
I also found datasets for which this problem occurs. These are:

486, 558, 664, 671, 673, 674, 689, 691, 700, 703, 704, 709

I  also found several other formatting errors:

* attributes starting with non-alphabetic characters: 273, 274, 285, 383-388, 391, 392, 394, 395, 397, 515, 525, 1090, 1122-1166
* ranges after the definition of a numerical attribute: 312, 
* Whitespace as a delimiter: 571, 579-658, 
* Whitespace as a delimiter in a categorical attribute description: 1077-1088

@joaquinvanschoren I can clean up the datasets from issues 1, 3, 4, 5 and send them to you so you can replace them. But I do not know what to do with the datasets in issue 2.

**Comment by jaksmid** [comment] 2015-03-02 08:57
The issue with cleaning is that they could still reference URL of the origin of the dataset.
This could lead to inconsistency as you would have cleaned dataset version in the OpenMl and different version in the Origin. Probably only correct way would be to communicate with the owners so the cleanup will happen in both places.

But it would be good to refuse invalid datasets in the future to force authors to correct them beforehand.

**Comment by joaquinvanschoren** [comment] 2015-03-02 09:55
Sorry for the late reply. Lots of things happening at the same time...

* Invalid ARFF: this has been fixed for all new uploads (OpenML will now
load the ARFF file into weka prior to accepting it, and refuses files where
this fails), but I didn't get the time to go over all previous datasets to
fix them. Thanks for bringing this up so we can fix them now.
* OpenML is much more strict in ARFF definitions than most other
repositories. Even if the ARFF looks weird, the owners are unlikely to
replace them because they are already used by thousands of people (with a
lot of manual cleaning each time). In many other cases, the owners did NOT
offer the data as ARFF but likely in CSV or C45 format. In those cases,
another researcher (not the owner) typically generated the ARFF versions,
which eventually found their way to OpenML. It would be a lot of work to
trace down where they came from. To avoid dealing with all this, OpenML
simply hosts a 'cleaner' ARFF versions of all datasets to allow easy
automation. We guarantee that within OpenML you are always talking about
the exact same dataset (hence data versioning), but we cannot control what
happens outside of it. We do add a backlink to the original host wherever
possible. It's the best we can do...

As for the issues: if you can fix 1,3,4,5 and send me the datasets, that
would be fantastic! I will replace them, no problem. These are problems
that WEKA apparently solves internally, so there should be no problems.
Maybe you can name the files by their OpenML ID, or somehow let me know
what the original IDs were.

1) Should we just add missing value chars '?' in the ARFF file?
3) Yes, this is weird. Just remove the ranges.
4) I deactivated 571 as there is a prior version that is correct (198).
Note that the API now returns a 'status' field that reflects this. The
other ones can be fixed by replacing the whitespaces with commas.
5) Can be fixed by replacing whitespaces with commas.

For 2): What is the problem with attributes that start with numbers? They
seem to run just fine in current tools. Is this a Python-specific issue?
Actually, attributes starting with numbers are extremely common in
bio-informatics and chem-informatics, so I don't want to exclude them.

Thanks Matthias and Jakub, this is very helpful!

Cheers,
Joaquin

**Comment by mfeurer** [comment] 2015-03-02 10:01
Hi Joaquin,

okay, I will clean up the datasets and send them to you.

Regarding issue 1), I think I just have to remove some commas
Regarding issue 2), the stable specification says that an attribute must start with a alphabetic character: http://weka.wikispaces.com/ARFF+%28stable+version%29 . Because the specification says so, it is implemented like that in the python module.

**Comment by joaquinvanschoren** [comment] 2015-03-02 10:53
Hi Matthias, this python module you mention is an official pyhton module
for reading ARFF data?

**Comment by mfeurer** [comment] 2015-03-02 11:50
Hi Joaquin, there is no official python module to read ARFF files. I use [liac-arff](https://github.com/renatopp/liac-arff), but there are also [arff](https://pypi.python.org/pypi/arff/0.9) and [scipy.io.arff](http://docs.scipy.org/doc/scipy/reference/generated/scipy.io.arff.loadarff.html). I only tried liac-arff and scipy, and found liac-arff to raise less exceptions for the arff files from OpenML.

**Comment by mfeurer** [comment] 2015-03-03 14:29
Hi Joaquin,
here are the datasets: http://aad.informatik.uni-freiburg.de/~feurerm/openml_reformatting_datasets.zip

There is one hierarchy of directories for the problem type, and for the datasets. 

While I fixed most datasets, I couldn't do it for dataset [703](http://openml.org/d/703). The problem is that it has six attributes, but some lines have seven value. It turns out that this is an issue, as the file is accepted by the current stable version of WEKA. Can you please confirm this?

**Comment by joaquinvanschoren** [comment] 2015-03-03 14:31
Hi Matthias,

The thing is that we only started auto-checking after dataset 900 or so.
I'll double-check 703. If WEKA accepts that, then indeed this is an issue.

Cheers,
Joaquin

**Comment by joaquinvanschoren** [comment] 2015-04-15 22:16
Hi, 

All datasets have been replaced, and all associated runs have been removed.
For 703 I found a fixed version, which simply removed the instanced which had extra values.

Have fun :). Can we close this?

**Comment by mfeurer** [comment] 2015-04-17 13:03
Hi Joaquin,

thanks for updating the datasets. I did not yet check all of them, but so far they look fine. With regard to dataset 703 and WEKA accepting it:

Would WEKA still accept the invalid old version? If yes, then this issue should definitely not be closed. 

Otherwise, I can reopen it if I find some problems with the data.
Cheers,
Matthias

**Comment by joaquinvanschoren** [comment] 2015-04-17 14:11
WEKA could not load dataset 703 either.

**Comment by mfeurer** [comment] 2015-04-17 15:09
Then everything is fine so far:)

**Closed by mfeurer** 2015-04-17 15:09 UTC
