### ISSUE TITLE
data quality NumberOfSymbolicFeatures sometimes missing

### ISSUE THREAD

**Issue by jakob-r** [openml/OpenML#187] opened 2015-05-06 17:00 UTC
It seems that the data quality `NumberOfSymbolicFeatures` is saved in the wrong format looking at the results of the API-Call `http://www.openml.org/api/?f=openml.tasks&task_type_id=1`

1. It is always returned with as a real number `<oml:quality name="NumberOfSymbolicFeatures">36.0</oml:quality>`
2. There are cases with `<oml:quality name="NumberOfSymbolicFeatures">0.0</oml:quality>`
3. Sometimes it is missing completely - but what does that mean? It's unlikely that the value could not be determined I guess.

**Comment by berndbischl** [comment] 2015-05-06 19:01
@jakob-r 
Could you maybe add a uni test in the r package to check against this? We have a group for "complete tests with all server objects".

I know these are not perfect, and we have to restrict these tests to a much smaller subset, but just so we dont forget this issue.

**Comment by joaquinvanschoren** [comment] 2015-05-06 20:13
Thanks. We'll fix it. We'll also restart the other computation of the
advanced properties on monday.

**Comment by berndbischl** [comment] 2016-01-07 20:41
This seems to now be a duplicate of #224 
I will briefly check now again

**Comment by joaquinvanschoren** [comment] 2016-01-07 20:45
Yes this is definitely solved. There is the issue of unparseable datasets where this can still go wrong but we'll handle that separately.

**Closed by joaquinvanschoren** 2016-01-07 20:45 UTC
