### ISSUE TITLE
API call for all tasks

### ISSUE THREAD

**Issue by dominikkirchhoff** [openml/OpenML#116] opened 2014-10-07 17:10 UTC
Let's say I wanted to have all classification tasks whose data sets have not more than 10 features, that have predictive_accuracy as their measure and that use 1x10-fold CV. How do I get these as easily as possible? 

Right now (without a great amount of SQL-wizardry), we need to get the data qualities, subset them and receive data ids. With these ids we can look for tasks, but then we are stuck at the moment. We need to download all of them and sort those out that are not matching our conditions. An API call for this would be great (returning at least the measures, the evaluation procedure and the task type of each registered task, even better if it'd also return the data qualities). Would that be possible?

**Comment by berndbischl** [comment] 2015-01-14 08:36
What is the status on this? 

task.list is nice, i guess we only need to include the eval measure and the resampling strategy name in the output of the list?

**Comment by berndbischl** [comment] 2015-02-16 21:03
done?

**Comment by joaquinvanschoren** [comment] 2015-02-17 23:40
duplicate of 168, closing

**Closed** 2015-02-17 23:40 UTC
Labels: priority: highest
