### ISSUE TITLE
Add API call for user/delete

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#1063] opened 2020-10-02 14:48 UTC
We should give users the opportunity to close their account. 
This is now done manually and is time-consuming.

There is API code for that, but it's commented out:
https://github.com/openml/OpenML/blob/ef804bafecb54025a4a414a3eee930a275e6454e/openml_OS/models/api/v1/Api_user.php#L38

Can we bring this back? For now it would be great to only allow deletion for users which don't have shared assets (e.g. datasets,...), and return an error otherwise.

Later we should describe what to do it a user with assets decides to close the account.

**Comment by PGijsbers** [comment] 2020-10-19 10:55
Duplicate of #846. Feel free to re-open if you disagree.

**Closed by PGijsbers** 2020-10-19 10:55 UTC
