### ISSUE TITLE
Inconsistent flow

### ISSUE THREAD

**Issue by janvanrijn** [openml/OpenML#362] opened 2017-02-01 12:32 UTC
OpenML flow 1 is supposed to have no subflows nor parameters, yet it has many:
https://www.openml.org/f/1

Somehow, this database inconsistency has been introduced over the years. I have searched for other cases, but could not find any. 

We should figure out how this has happened and why this was possible.

**Comment by mfeurer** [comment] 2019-04-17 12:43
Closing this as a duplicate of #243.

**Closed by mfeurer** 2019-04-17 12:43 UTC
