### ISSUE TITLE
API returns nothing. Stochastic bug?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#509] opened 2017-11-04 10:30 UTC
Hm this only seems to appear sometimes. The listing calls give me the right results but sometimes I a completely empty page is returned.

For example:
If I open this url https://www.openml.org/api/v1/json/data/list/limit/100/status/active multiple times (e.g. 10 times), it gives me a completely empty page with a 50% chance.

This seems to happen for almost all listing calls? And causes many failing unit tests.

**Comment by mfeurer** [comment] 2017-11-04 19:33
I can confirm this and it has happened to me a lot. According to @janvanrijn this is because of high server load. As a temporary fix I added a loop around the actual call to OpenML which retries the call 20 times after waiting between 0.1 and 2 seconds, this seems to help and make the API stable.

**Comment by joaquinvanschoren** [comment] 2017-11-04 21:23
It's good to make the APIs more stable, but this is a server issue, and it really shouldn't do this. 

It took a look, and the server is very busy because of a specific type of query executed hundreds of times. It is a query that finds the specific setup ID belonging to a specific (long) list of hyperparameter settings. It often has over 50 sub-queries (for 50 hyperparameter values). It sometimes crashes because the temporary table it builds is too large. That's why you got an empty response.

I fixed that issue, so the query doesn't crash anymore. Server load has also normalized. The query still pops up frequently, but the server is handling it now.

@janvanrijn That query is still slow (takes about 30 sec).  Is this indeed a query that is executed all the time? Then I could try to optimize it. 

@mfeurer I'm OK with the API 'retrying', but it this it made the problem worse without us noticing it right away. Could you please detect when the server returns an empty result and let us know so we can fix it? Thanks!

Please rerun your unit tests and close if it's better now.

**Comment by mfeurer** [comment] 2017-11-05 10:02
I removed the retries and it looks like most queries are actually working again. I'm having spontaneous issues with `setup_exists` which are very annoying because I have to manually restart those jobs. At least in python `setup_exists` is called for every run that is executed, and I would expect R does the same?

**Comment by joaquinvanschoren** [comment] 2017-11-07 16:15
@janvanrijn Is it necessary to actually retrieve the setup with `setup_exists`? Checking if it exists could be faster than retrieving the whole setup?

**Comment by joaquinvanschoren** [comment] 2017-11-07 16:20
Just to illustrate what's happening: This slow query is running 15 times(!) in parallel right now, the exact same query. Some process is calling it multiple times I guess.
```
SELECT `sid`,`implementation_id`,`nr_parameters`, `i54781`.`value` AS `i54781`, 
`i54785`.`value` AS `i54785`, `i54786`.`value` AS `i54786`, `i54787`.`value` AS 
`i54787`FROM `algorithm_setup` AS `s` LEFT JOIN (SELECT `setup`, COUNT(*) AS 
`nr_parameters` FROM `input_setting` GROUP BY `setup`) AS `p` ON `s`.`sid` = `p`.`setup` 
LEFT JOIN `input_setting` `i54781` ON `i54781`.`setup` = `s`.`sid` AND `i54781`.`input_id` = 
"54781" LEFT JOIN `input_setting` `i54785` ON `i54785`.`setup` = `s`.`sid` AND 
`i54785`.`input_id` = "54785" LEFT JOIN `input_setting` `i54786` ON `i54786`.`setup` = 
`s`.`sid` AND `i54786`.`input_id` = "54786" LEFT JOIN `input_setting` `i54787` ON 
`i54787`.`setup` = `s`.`sid` AND `i54787`.`input_id` = "54787" WHERE `implementation_id` =
 "5890" AND IFNULL(`nr_parameters`,0) = 4 AND `i54781`.`value` = '2' AND `i54785`.`value` = 
'1' AND `i54786`.`value` = 'Mersenne-Twister' AND `i54787`.`value` = 'Inversion' LIMIT 0,1
```

**Comment by joaquinvanschoren** [comment] 2017-11-07 23:30
I think I found a solution to make this a lot faster and made a PR
https://github.com/openml/website/pull/204

@janvanrijn: please check. I'm not sure how to properly test this.

**Comment by janvanrijn** [comment] 2017-11-08 11:10
Can you describe what you changed there? I do not really see anything that changes the behaviour or the performance

**Comment by joaquinvanschoren** [comment] 2017-11-08 11:22
The behavior should be exactly the same. In my test the old query took 36 seconds on the main server, the new one took 0.001 seconds.

What it changes is that it removes a left join with a large temporary table (input_settings grouped by setup), and instead just adds a constraint that checks whether the number of hyperparameter settings is exactly the same as requested. That's only a quick look-up for a few setups.

**Comment by joaquinvanschoren** [comment] 2017-11-08 11:24
For testing on the main server, here is updated version of the query above, so you can compare:
```
SELECT `sid`,`implementation_id`, `i54781`.`value` AS `i54781`, `i54785`.`value` AS `i54785`, `i54786`.`value` AS `i54786`, `i54787`.`value` AS `i54787`FROM `algorithm_setup` AS `s` 
LEFT JOIN `input_setting` `i54781` ON `i54781`.`setup` = `s`.`sid` AND `i54781`.`input_id` = 
"54781" LEFT JOIN `input_setting` `i54785` ON `i54785`.`setup` = `s`.`sid` AND 
`i54785`.`input_id` = "54785" LEFT JOIN `input_setting` `i54786` ON `i54786`.`setup` = 
`s`.`sid` AND `i54786`.`input_id` = "54786" LEFT JOIN `input_setting` `i54787` ON 
`i54787`.`setup` = `s`.`sid` AND `i54787`.`input_id` = "54787" WHERE `implementation_id` = 
"5890" AND (SELECT COUNT(*) FROM `input_setting` where `setup` = `s`.`sid`) = 4 AND 
`i54781`.`value` = '2' AND `i54785`.`value` = '1' AND `i54786`.`value` = 'Mersenne-Twister' AND 
`i54787`.`value` = 'Inversion' LIMIT 0,1
```

**Comment by janvanrijn** [comment] 2017-11-08 12:45
I seem to understand what you are doing here. This was the slow part in the old query, partly because of the group by, partly because it was in the left join:
`'LEFT JOIN (SELECT setup, COUNT(*) AS nr_parameters FROM input_setting GROUP BY setup) AS p ON s.sid = p.setup`
And this is replaced by this , eliminating both mentioned problems. 
`SELECT COUNT(*) FROM input_setting where setup = s.sid`

I guess we can get rid of the IFNULL in this case too, because if the setup does not have any parameters, this query automatically fills in a 0. Can you confirm this? 

If this is all well, we should merge with development branch and run python unit tests on the dev server. 

Thanks for improving this query. It solves a horribly annoying scalability issue and makes the query way more readable.

**Comment by joaquinvanschoren** [comment] 2017-11-08 12:48
Exactly, and I did remove the IFNULL in my PR :)
Please go ahead and run the unit tests. The sooner we can merge this the better :).

**Comment by janvanrijn** [comment] 2017-11-08 13:05
Unit tests are finished. All the relevant tests seem to work fine. 

However there are some other tests that crashed (maybe due to other fixes in development branch). This should be fixed before we can pull the update on live.

**Comment by joaquinvanschoren** [comment] 2017-11-09 12:50
Pulled on the main server now. Server load is normal again. 

Can you check and close if ok?

**Comment by janvanrijn** [comment] 2019-04-15 17:16
This one can be closed permanently, I suppose (problem was too many database connections, and the error was not properly catched and communicated. Now it usually mentions it)

**Closed by janvanrijn** 2019-04-15 17:16 UTC
Labels: bug, priority: highest
