### ISSUE TITLE
Support multilabel tasks

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/OpenML#497] opened 2017-10-18 08:39 UTC
We have some (tagged) multilabel datasets but cannot yet create tasks on them.
https://www.openml.org/search?q=tags.tag%3A2016_multilabel_r_benchmark_paper&type=data

@janvanrijn: should we create a separate multilabel task, or extend the existing classification task?
My intuition is that a separate task may be better, since multilabel models are evaluated differently. At the very least, you need to define how to average out the performances on individual labels (micro/macro/weighted,...)

@berndbischl, @giuseppec, @PhilippPro, @QuayAu: you were also interested in this, I believe. What would be most useful for you?

**Comment by PhilippPro** [comment] 2017-10-19 10:49
If it supports the multilabel measures that are implemented here: http://mlr-org.github.io/mlr-tutorial/devel/html/measures/index.html

**Comment by mfeurer** [comment] 2019-04-17 12:48
Closing this as a duplicate of #142.

**Closed by mfeurer** 2019-04-17 12:48 UTC
