### ISSUE TITLE
Probelms Using ListOMLTasks

### ISSUE THREAD

**Issue by MerlinDerEchte** [openml/OpenML#860] opened 2018-11-12 10:48 UTC
I have an Issue concerning the function "listOMLTasks". 
When i execute my code which i have already done 100 times before and everything worked, i get the exception

 "Error: lexical error: invalid char in json text.
                                       <div style="border:1px solid #9
                     (right here) ------^"
Do you know what could be the reason for that?

**Comment by PhilippPro** [comment] 2018-11-12 12:53
Request is from R (@giuseppec )
```
listOMLTasks()
Fehler: lexical error: invalid char in json text.
                                       <div style="border:1px solid #9
                     (right here) ------^
```

**Comment by giuseppec** [comment] 2018-11-12 14:00
@joaquinvanschoren, @janvanrijn I think this bug is due to the PHP change, which breaks the JSON format in https://www.openml.org/api/v1/json/evaluationmeasure/list , https://www.openml.org/api/v1/json/run/list and https://www.openml.org/api/v1/json/evaluation/list could you please fix?

**Comment by mfeurer** [comment] 2018-11-12 14:01
I don't think this is a JSON-only issue. Please also have a look at this API call: https://test.openml.org/api/v1/xml/data/features/2

**Comment by mfeurer** [comment] 2018-11-12 14:02
Sorry, wrong button.

**Comment by jnothman** [comment] 2018-11-12 14:32
A related issue is at https://github.com/scikit-learn/scikit-learn/issues/12504, where it breaks any calls to scikit-learn's fetch_openml. This needs urgent fixing, and then regression testing.

**Comment by joaquinvanschoren** [comment] 2018-11-12 16:13
Sorry, this was caused by a pull that overwrote a production server configuration, causing it to act like the development server. Fixed now!

**Closed** 2018-11-21 14:11 UTC
